### Updates an existing patient entity
PUT http://localhost:4004/api/patients/71aaef3c-f1e0-47d0-9f7b-f05e392c93b4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Pradipta Das Updated",
  "email": "pradiptaaa@example.com",
  "address": "123 main goli",
  "dateOfBirth": "1995-09-09"
}

###